### ISSUE TITLE
yarn build failed with errors

### ISSUE THREAD

**Issue by PsidomPC** [joeldenning/single-spa-examples#57]
Cloned the github repo instead of following the one in README as it errors out as well, but when I do `yarn build`, I ran into the following error, what could be the issue? I already reinstalled nodejs to be the latest LTS:

> yarn run v1.9.4
$ rimraf build && yarn ember-install && yarn build-ember && yarn build-vanilla && yarn build-webpack
$ cd src/ember-app && yarn && cd ../..
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > ember-data@2.14.11" has unmet peer dependency "ember-inflector@^2.0.0".
[5/5] Building fresh packages...
$ bower install
$ cd src/ember-app && ember build --output-path ../../build/ember-app/ --environment production && cd ../..
cleaning up...
Build failed.
Build Canceled: Broccoli Builder ran into an error with `Funnel` plugin. 💥
ENOENT: no such file or directory, lstat 'C:\Users\XXX\VuePwa\single-spa-examples\src\ember-app\tmp\funnel-input_base_path-WvLdHVls.tmp\bower_components\single-spa-ember\amd\single-spa-ember.js'
Error: ENOENT: no such file or directory, lstat 'C:\Users\XXX\VuePwa\single-spa-examples\src\ember-app\tmp\funnel-input_base_path-WvLdHVls.tmp\bower_components\single-spa-ember\amd\single-spa-ember.js'
    at Object.fs.lstatSync (fs.js:941:11)
    at symlinkWindows (C:\Users\XXX\VuePwa\single-spa-examples\src\ember-app\node_modules\symlink-or-copy\index.js:106:25)
    at Function.symlinkOrCopySync [as sync] (C:\Users\XXX\VuePwa\single-spa-examples\src\ember-app\node_modules\symlink-or-copy\index.js:63:5)
    at Funnel._copy (C:\Users\XXX\VuePwa\single-spa-examples\src\ember-app\node_modules\broccoli-funnel\index.js:492:19)
    at Funnel.processFile (C:\Users\XXX\VuePwa\single-spa-examples\src\ember-app\node_modules\broccoli-funnel\index.js:475:8)
    at Funnel.applyPatch [as _applyPatch] (C:\Users\XXX\VuePwa\single-spa-examples\src\ember-app\node_modules\broccoli-funnel\index.js:389:12)
    at Funnel.<anonymous> (C:\Users\XXX\VuePwa\single-spa-examples\src\ember-app\node_modules\broccoli-funnel\index.js:343:10)
    at Array.forEach (<anonymous>)
    at Funnel.processFilters (C:\Users\XXX\VuePwa\single-spa-examples\src\ember-app\node_modules\broccoli-funnel\index.js:342:11)
    at Funnel.build (C:\Users\XXX\VuePwa\single-spa-examples\src\ember-app\node_modules\broccoli-funnel\index.js:258:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by joshalling** [comment]
@PsidomPC I ran into the same error when I ran `yarn build`. It seems to be a problem specific to the ember framework. You can still run `yarn start` and the app will work with all the frameworks except ember.

**Comment by windust211** [comment]
same with my situation, now i am stuck by two issues.One is how to remove the emberjs part  from the project and continue my building work, the other is how to install them online when building is done, thx!

**Comment by JerzyLesniak** [comment]
I have same problem and when i run ```yarn start```, webpack server starts running but all i can see at localhost:8080 is ```404 page not found```. I'm was tryin to build ember&react app and now i don't think this library is good solution.

**Comment by filoxo** [comment]
@JerzyLesniak before making accusations that "this library is [not] a good solution", try actually solving this issue yourself. You're essentially asking for others to fix it for you, and that's not a sustainable model for open source. The current maintainers of single-spa don't use ember and I'm sure they'd appreciate help from anyone who knows ember well to fix this issue. 

To everyone else, the error as I see it from the logs others have posted is that `bower_components\single-spa-ember\amd\single-spa-ember.js` doesn't exist. Maybe something/someone needs to run bower first? Clearly the issue is with the ember configuration, not necessarily single-spa.

**Comment by resourceF** [comment]
> @PsidomPC I ran into the same error when I ran `yarn build`. It seems to be a problem specific to the ember framework. You can still run `yarn start` and the app will work with all the frameworks except ember.
What should I do if I want to build?
