### ISSUE TITLE
cannot run build in windows

### ISSUE THREAD

**Issue by forever-chen** [joeldenning/single-spa-examples#70]
cleaning up...
Build failed.
Build Canceled: Broccoli Builder ran into an error with `Funnel` plugin. 💥
ENOENT: no such file or directory, lstat 'F:\learn\single-spa\single-spa-examples\src\ember-app\tmp\funnel-input_base_path-EiMffosU.tmp/bower_components/single-spa-ember/amd/single-spa-ember.js'
Error: ENOENT: no such file or directory, lstat 'F:\learn\single-spa\single-spa-examples\src\ember-app\tmp\funnel-input_base_path-EiMffosU.tmp/bower_components/single-spa-ember/amd/single-spa-ember.js'
    at Object.lstatSync (fs.js:841:3)
    at symlinkWindows (F:\learn\single-spa\single-spa-examples\src\ember-app\node_modules\symlink-or-copy\index.js:106:25)
    at Function.symlinkOrCopySync [as sync] (F:\learn\single-spa\single-spa-examples\src\ember-app\node_modules\symlink-or-copy\index.js:63:5)
    at Funnel._copy (F:\learn\single-spa\single-spa-examples\src\ember-app\node_modules\broccoli-funnel\index.js:492:19)
    at Funnel.processFile (F:\learn\single-spa\single-spa-examples\src\ember-app\node_modules\broccoli-funnel\index.js:475:8)
    at Funnel.applyPatch [as _applyPatch] (F:\learn\single-spa\single-spa-examples\src\ember-app\node_modules\broccoli-funnel\index.js:389:12)
    at Funnel.<anonymous> (F:\learn\single-spa\single-spa-examples\src\ember-app\node_modules\broccoli-funnel\index.js:343:10)
    at Array.forEach (<anonymous>)
    at Funnel.processFilters (F:\learn\single-spa\single-spa-examples\src\ember-app\node_modules\broccoli-funnel\index.js:342:11)
    at Funnel.build (F:\learn\single-spa\single-spa-examples\src\ember-app\node_modules\broccoli-funnel\index.js:258:10)

**Comment by internettrans** [comment]
See related #69
